# Generated by Django 3.1.7 on 2021-03-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('zone', models.TextField()),
                ('hostname', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('linkshell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.linkshell')),
            ],
        ),
    ]
