# Generated by Django 3.1.7 on 2021-03-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
