# Generated by Django 3.1.7 on 2021-03-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20210321_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='character',
            field=models.TextField(default='Character_Name'),
            preserve_default=False,
        ),
    ]
