# Generated by Django 3.1.7 on 2021-03-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_member_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='linkshell',
            new_name='linkshell_id',
        ),
        migrations.AlterField(
            model_name='member',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
