# Generated by Django 3.1.7 on 2021-03-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20210323_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='linkshell_id',
            new_name='linkshell',
        ),
    ]
